import type { ContentEntry, ComponentMap, CodegenOpts, Field } from './types.js';
import { collectionToTs, fieldUsesImage, fieldsToZodObject, blockToDiscriminatedUnion } from './codegen.js';

// ─── Shared component detection ──────────────────────────────────────────────

/**
 * Returns the set of component names that are referenced directly on
 * collection-level fields in two or more collections.
 */
export function findSharedComponents(
  content: ContentEntry[],
  _components: ComponentMap,
): Set<string> {
  const usageCount = new Map<string, number>();

  for (const entry of content) {
    const seen = new Set<string>();
    for (const field of entry.fields ?? []) {
      const compName = (field as any)._component as string | undefined;
      if (compName && !seen.has(compName)) {
        seen.add(compName);
        usageCount.set(compName, (usageCount.get(compName) ?? 0) + 1);
      }
    }
  }

  const shared = new Set<string>();
  for (const [name, count] of usageCount) {
    if (count >= 2) shared.add(name);
  }
  return shared;
}

// ─── Shared schema emitter ───────────────────────────────────────────────────

function emitSharedSchema(
  compName: string,
  field: Field,
  opts: CodegenOpts,
): string {
  const needsImage = fieldUsesImage(field);
  const innerOpts: CodegenOpts = { ...opts, isGlob: true }; // shared schemas use glob context for image()

  if (field.type === 'block') {
    // block schemas emit z.array(...).default([]) — no extra .optional()
    const body = blockToDiscriminatedUnion(field, innerOpts);
    if (needsImage) {
      return `const ${compName}Schema = (image: SchemaContext['image']) =>\n  ${body};`;
    }
    return `const ${compName}Schema = \n  ${body};`;
  }

  const body = fieldsToZodObject(field.fields ?? [], innerOpts);
  // Shared schemas are always optional (they're used as top-level fields)
  const schema = `${body}.optional()`;

  if (needsImage) {
    return `const ${compName}Schema = (image: SchemaContext['image']) =>\n  ${schema};`;
  }
  return `const ${compName}Schema = \n  ${schema};`;
}

// ─── File assembler ──────────────────────────────────────────────────────────

export function assembleFile(
  content: ContentEntry[],
  components: ComponentMap,
  opts: CodegenOpts,
): string {
  // Only collection/file entries become Astro collections (groups are flattened by normalizeConfig)
  const entries = content.filter((e) => e.type === 'collection' || e.type === 'file');

  const sharedComponents = findSharedComponents(entries, components);

  const lines: string[] = [];

  lines.push('// THIS FILE IS AUTO-GENERATED by astro-pagescms');
  lines.push('// Source: .pages.yml — do not edit manually, changes will be overwritten on next build');
  lines.push('');
  lines.push("import { file, glob } from 'astro/loaders';");
  lines.push("import { z } from 'astro/zod';");
  lines.push("import type { SchemaContext } from 'astro:content';");
  lines.push("import { defineCollection } from 'astro:content';");

  // Emit shared component schemas
  const sharedSchemaDefs: string[] = [];
  for (const compName of sharedComponents) {
    const compField = components[compName];
    if (compField) {
      sharedSchemaDefs.push(emitSharedSchema(compName, compField, opts));
    }
  }
  if (sharedSchemaDefs.length > 0) {
    lines.push('');
    lines.push('// Shared component schemas');
    lines.push(...sharedSchemaDefs);
  }

  // Emit each collection
  lines.push('');
  lines.push('// Collections');
  const collectionNames: string[] = [];
  for (const entry of entries) {
    const varName = camelCase(entry.name);
    collectionNames.push(varName);
    const def = collectionToTs(entry, components, sharedComponents, opts);
    lines.push(`const ${varName} = ${def};`);
  }

  lines.push('');
  lines.push(`export const collections = { ${collectionNames.join(', ')} };`);
  lines.push('');

  return lines.join('\n');
}

function camelCase(name: string): string {
  return name.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}
